apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hungryman-notify
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: where-for-dinner-availability
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    networking.knative.dev/visibility: cluster-local
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  resources:     
    requests:         
      memory: "500M"
      cpu: "100m"
    limits:         
      memory: "750M"
      cpu: "1.5"         
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"   
  serviceClaims:      
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: rmq-hungryman
  source:
    git:
      url: https://github.com/gm2552/hungryman.git
      ref:
        branch: main
    subPath: hungryman-notify