where-for-dinner:
  notifications:
    logger:
       enabled: true

server.port: 8085

spring:
  application:
    name: hungryman-notify

  cloud: 
    function:
      definition: notifyAvailability  
    stream:
      defaultBinder: rabbit
      bindings: 
        notifyAvailability-in-0: 
          destination: hungryman-search-result
          group: hungryman-notify-group
          consumer: 
            maxAttempts: 4
            backOffInitialInterval: 15000
            backOffMaxInterval: 60000 
            
---

spring:
  config.activate.on-profile: kafka
  
  cloud: 
    stream:
      defaultBinder: kafka

---

spring:
  config.activate.on-profile: kinesis
  
  cloud: 
    stream:
      defaultBinder: kinesis