spring.cloud.kubernetes.enabled: false

where-for-dinner:
  namespace: ${spring.cloud.kubernetes.client.namespace}
  ui:
    uri: http://hungryman-ui.${where-for-dinner.namespace}/
  search:
    uri: http://hungryman-search.${where-for-dinner.namespace}/
  availability:
    uri: http://hungryman-availability.${where-for-dinner.namespace}/

spring:
  application:
    name: hungryman-api-gateway

  session:
    timeout: 60m
  cloud:
    gateway:
      forwarded.enabled: false
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
      - id: where-for-dinner_search_route
        uri: ${where-for-dinner.search.uri}
        predicates:
        - Path=/api/search/**      
        - Host=hungryman**.**
        filters:
        - TokenRelay=
        - RewritePath=/api/search(?<segment>/?.*), $\{segment}
        - RemoveRequestHeader=Forwarded
      - id: where-for-dinner_availability_route
        uri: ${where-for-dinner.availability.uri}
        predicates:
        - Path=/api/availability/** 
        - Host=hungryman**.**
        filters:
        - TokenRelay=
        - RewritePath=/api/availability(?<segment>/?.*), $\{segment}
        - RemoveRequestHeader=Forwarded
      - id: where-for-dinner_ui_route
        uri: ${where-for-dinner.ui.uri}
        predicates:
        - Host=hungryman**.**
        - Path=/diningsearch
      - id: where-for-dinner_ui_route
        uri: ${where-for-dinner.ui.uri}
        predicates:
        - Host=hungryman**.**
        - Path=/**

---
spring:
  config.activate.on-profile: local


#Local profile forwards to local instances  
where-for-dinner:
  namespace: workloads
  ui:
    uri: http://localhost:3000/   # default used by npm start
  search:
    uri: http://localhost:8081/
  availability:
    uri: http://localhost:8082/