#@ load("@ytt:data", "data")
---
apiVersion: sso.apps.tanzu.vmware.com/v1alpha1
kind: ClientRegistration
metadata:
   name: hungryman-client-registration
   namespace: #@ data.values.workloadNamespace
   labels:
     services.apps.tanzu.vmware.com/class: clientreg-hungryman 
spec:
   authServerSelector:
      matchLabels:
         name: #@ data.values.appSSOName
   redirectURIs: 
     - #@ data.values.appWorkloadURL + '/login/oauth2/code/sso'
   requireUserConsent: false
   clientAuthenticationMethod: client_secret_basic
   authorizationGrantTypes:
      - "client_credentials"
      - "authorization_code"
   scopes:
      - name: "openid"
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaimPolicy
metadata:
  name: hungryman-client-registration-cross-namespace
  namespace: #@ data.values.workloadNamespace
spec:
  consumingNamespaces:
  - '*'
  subject:
    group: sso.apps.tanzu.vmware.com
    kind: ClientRegistration
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: #@ data.values.appSSOName
  namespace: #@ data.values.workloadNamespace
spec:
  ref:
    apiVersion: sso.apps.tanzu.vmware.com/v1alpha1
    kind: ClientRegistration
    name: hungryman-client-registration
    namespace: #@ data.values.workloadNamespace
