#@ load("@ytt:data", "data")

#@ if data.values.dynamicCache == False:
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaimPolicy
metadata:
  name: hungryman-bitnami-redis-cross-namespace
  namespace: #@ data.values.serviceNamespace
spec:
  consumingNamespaces:
  - '*'
  subject:
    group: ""
    kind: Secret
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  name: #@ data.values.cacheName
  namespace: #@ data.values.workloadNamespace
spec:
  classRef:
    name: bitnami-redis-hungryman
#@ else: 
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  name: #@ data.values.cacheName
  namespace: #@ data.values.workloadNamespace
spec:
  classRef:
    name: bitnami-redis-hungryman
#@ end