#@ load("@ytt:data", "data")

#@ if data.values.dynamicMsgBroker == False:
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaimPolicy
metadata:
  name: hungryman-rabbitmqcluster-cross-namespace
  namespace: #@ data.values.serviceNamespace
spec:
  consumingNamespaces:
  - '*'
  subject:
    group: rabbitmq.com
    kind: RabbitmqCluster
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  name: #@ data.values.msgbrokerName
  namespace: #@ data.values.workloadNamespace
spec:
  classRef:
    name: rabbitmq-hungryman
#@ else:  
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  name: #@ data.values.msgbrokerName
  namespace: #@ data.values.workloadNamespace
spec:
  classRef:
    name: #@ data.values.dynamicMsgBrokerClass
  parameters:
    replicas: #@ data.values.numRabbitMQClusterNodes 
    serviceNamespace: #@ data.values.serviceNamespace
#@ end
